language: python
python:
  - '2.7'
  - '3.2'
before_install:
  - sudo apt-get update -qq
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then
      sudo apt-get install python-numpy python-matplotlib python-pythonmagick
    else
      sudo apt-get install python3-matplotlib python3-numpy
    fi
virtualenv:
  system_site_packages: true
install:
  - python setup.py install
script: nosetests
cache: apt
