language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-matplotlib python-pythonmagick
  - sudo apt-get install --qq python3-matplotlib python3-numpy
virtualenv:
  system_site_packages: true
install:
  - pip install .
script: nosetests
cache: apt
