language: python
python:
  - '2.7'
  - '3.2'
before_install:
  - sudo apt-get update -qq
 - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install python-numpy python-matplotlib python-pythonmagick python-wand; fi
 - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install python3-matplotlib python3-numpy python-wand; fi
virtualenv:
  system_site_packages: true
install:
  - python setup.py install
script: nosetests
cache: apt
